name: CI/CD pipeline

on:
  push:
    branches:
      - lab9
      - main
  pull_request:
    branches:
      - lab9
      - main
  workflow_dispatch:
    inputs:
      run-quality:
        description: 'Run quality?'
        required: false
        default: 'false' 
      run-tests:
        description: 'Run tests?'
        required: false
        default: 'false'
    
env:
  BUILD_ARTIFACT_NAME: "package"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install corepack
        run: npm install -g corepack

      - name: Enable corepack
        run: corepack enable

      - name: Prepare corepack for pnpm
        run: corepack prepare pnpm@latest-8 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  quality_and_tests:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install corepack
        run: npm install -g corepack

      - name: Enable corepack
        run: corepack enable

      - name: Prepare corepack for pnpm
        run: corepack prepare pnpm@latest-8 --activate

      - name: Install dependencies
        run: pnpm install

      - name: type_check
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.run-quality == 'true'
        run: pnpm type-check
      
      - name: lint
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.run-quality == 'true'
        run: pnpm lint

      - name: test
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.run-tests == 'true'
        run: pnpm test


  deploy-qa:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
