name: CI/CD pipeline

on:
  push:
    branches:
      - lab9
    
env:
  BUILD_ARTIFACT_NAME: "package"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Dependencies
        run: 
          corepack enable
          corepack prepare pnpm@latest-8 --activate
          pnpm config set store-dir .pnpm-store
          pnpm install
      
      - name: build
        run: pnpm build

  deploy-qa:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
